version: '3'
services:
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    command: mysqld --sql_mode=""
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./test_db_init.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - '3306:3306'
